# Generated by Django 3.1.6 on 2022-03-02 17:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20220302_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='submission',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
