# Generated by Django 3.1.6 on 2022-03-02 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220302_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='publish_date',
            new_name='pub_date',
        ),
    ]
